# VERSION 1.0
# AUTHOR: Mathieu Bretaud
# DESCRIPTION: Docker Jenkins
# BUILD: docker build --tag jenkins_master:{{ jenkins_master_image_version }} .
# RUN: docker run -it jenkins_master:{{ jenkins_master_image_version }}
# SOURCE:

FROM jenkins:{{ jenkins_version }}

MAINTAINER DatascienceTeam

ENV DATASCIENCE_NO_PROXY="{{ proxy_env.no_proxy }}"
ENV DATASCIENCE_PROXY_HOST="{{ proxy_env.host }}"
ENV DATASCIENCE_PROXY_PORT="{{ proxy_env.port }}"
ENV DATASCIENCE_GIT_TOKEN="{{ github_token }}"
ENV JAVA_OPTS="-Djava.awt.headless=true -Duser.timezone='{{ timezone }}'"
ENV http_proxy="{{ proxy_env.http_proxy }}"
ENV https_proxy="{{ proxy_env.https_proxy }}"
ENV no_proxy="{{ proxy_env.no_proxy }}"

ENV SMTP_PORT 25

COPY plugins.txt /usr/share/jenkins/plugins.txt

RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt

COPY generate-configuration.pl /tmp/generate-configuration.pl
RUN perl /tmp/generate-configuration.pl

COPY override/* /usr/share/jenkins/ref/

USER root
RUN ln -snf /usr/share/zoneinfo/{{ timezone }} /etc/localtime && echo {{ timezone }} > /etc/timezone

RUN apt-get update && apt-get install -y socat vim net-tools sshpass
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y postfix mailutils rsyslog
RUN apt-get install -y python-pip
RUN pip install nose
RUN pip install pep8
RUN pip install pyflakes

COPY postfix/main.cf /etc/postfix/main.cf
COPY postfix/mailname /etc/mailname
COPY postfix/resolv.conf /etc/resolv.conf

RUN /etc/init.d/postfix reload

USER jenkins

# Email port (SMTP)
EXPOSE $SMTP_PORT
