---

- name: Status containers
  shell: "docker-compose -f {{ jenkins_volume_path }}/working-dir/docker-compose.yml ps"
  register: result_status

- debug: msg="{{result_status.stdout_lines}}"
  failed_when: "'Exit' in result_status.stdout"

