# VERSION 1.0
# AUTHOR: Mathieu Bretaud
# DESCRIPTION: Docker Jenkins
# BUILD: docker build --tag jenkins_master_data:{{ jenkins_master_image_version }} .
# RUN: docker run -it jenkins_master_data:{{ jenkins_master_image_version }}
# SOURCE:

FROM centos:6

MAINTAINER DatascienceTeam

ENV DATASCIENCE_NO_PROXY="{{ proxy_env.no_proxy }}"
ENV DATASCIENCE_PROXY_HOST="{{ proxy_env.host }}"
ENV DATASCIENCE_PROXY_PORT="{{ proxy_env.port }}"
ENV DATASCIENCE_GIT_TOKEN="{{ github_token }}"
ENV http_proxy="{{ proxy_env.http_proxy }}"
ENV https_proxy="{{ proxy_env.https_proxy }}"
ENV JENKINS_HOME="{{ jenkins_home }}"

ENV SMTP_PORT 25

RUN ln -snf /usr/share/zoneinfo/{{ timezone }} /etc/localtime && echo {{ timezone }} > /etc/timezone

RUN adduser -u 1000 jenkins --home $JENKINS_HOME

RUN mkdir $JENKINS_HOME/.ssh
RUN mkdir $JENKINS_HOME/.sbt
RUN mkdir $JENKINS_HOME/jobs
RUN mkdir $JENKINS_HOME/jobs/ADMIN-seed_job

COPY home/ssh/* $JENKINS_HOME/.ssh/
COPY home/workflow-libs $JENKINS_HOME/workflow-libs
COPY home/jobs/ADMIN-seed_job.xml $JENKINS_HOME/jobs/ADMIN-seed_job/config.xml

RUN yum -y install perl

COPY generate-configuration.pl /tmp/generate-configuration.pl
RUN perl /tmp/generate-configuration.pl

RUN chmod 600 $JENKINS_HOME/.ssh/id_rsa

RUN chown -R jenkins:jenkins $JENKINS_HOME

# Email port (SMTP)
EXPOSE $SMTP_PORT

CMD tail -f /dev/null
